# Generated by Django 3.0.4 on 2020-03-08 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200224_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
    ]
